### ISSUE TITLE
Remote Sensing Generative Foundation Models

### ISSUE THREAD

**Issue by YangPanHZAU** [Jack-bo1220/Awesome-Remote-Sensing-Foundation-Models#1]
有关生成式遥感基础模型，以下有两个相关的project，可以合并进来
https://github.com/RubenGres/Seg2Sat

Espinosa M, Crowley E J. Generate Your Own Scotland: Satellite Image Generation Conditioned on Maps[J]. (NeurIPS) 2023 Workshop on Diffusion Models. https://github.com/toastyfrosty/map-sat

**Comment by Jack-bo1220** [comment]
已更新，非常感谢！
