### ISSUE TITLE
Image-text retrieval dataset

### ISSUE THREAD

**Issue by JorisCod** [Jack-bo1220/Awesome-Remote-Sensing-Foundation-Models#18]
LuoJiaHOG: A Hierarchy Oriented Geo-aware Image Caption Dataset for Remote Sensing Image-Text Retrieval
https://arxiv.org/pdf/2403.10887.pdf

They refer to GeoRSClip, which is the CLIP model (VLM) trained on RS5M:
https://arxiv.org/abs/2306.11300
(You have the dataset in the list, but It seems they recently added the name GeoRSClip)

**Comment by JorisCod** [comment]
Relating to image retrieval, there's also this:
https://arxiv.org/abs/2401.07782
Exploring Masked Autoencoders for Sensor-Agnostic Image Retrieval in Remote Sensing
CSMAE models

**Comment by Jack-bo1220** [comment]
We updated them. Thanks!
