### ISSUE TITLE
SAMRS: a large-scale RS foundation model pretraining dataset.

### ISSUE THREAD

**Issue by DotWang** [Jack-bo1220/Awesome-Remote-Sensing-Foundation-Models#21]
This is a large-scale RS segmentation pretraining dataset generated by SAM.  

paper: https://arxiv.org/abs/2305.02034

code: https://github.com/ViTAE-Transformer/SAMRS

It has pretrained a series of  RS segmentation foundation models, which are included in the comparison in SkySense (https://arxiv.org/abs/2312.10115).

In addition, it contains multitask labels (object detection, instance segmentation, semantic segmentation), and has been used to develop RS universal vision foundation model by MTP (https://arxiv.org/abs/2403.13430).

**Comment by Jack-bo1220** [comment]
Thanks, we added it.

**Comment by DotWang** [comment]
@Jack-bo1220 Hi, the repo of RSP is https://github.com/ViTAE-Transformer/RSP instead of https://github.com/ViTAE-Transformer/Remote-Sensing-RVSA
