### ISSUE TITLE
Major TOM dataset

### ISSUE THREAD

**Issue by aliFrancis** [Jack-bo1220/Awesome-Remote-Sensing-Foundation-Models#27]
Hey guys,

Great work on this resource, it's super useful! Just wanted to bring your attention to our dataset project [Major TOM](https://huggingface.co/Major-TOM), which has over 60TB of EO data, with future additions on their way. There is a preprint paper about it available [here](https://arxiv.org/abs/2402.12095). 

If you could include this in the repo we'd be grateful.

**Comment by Jack-bo1220** [comment]
Thanks a lot. We have added it!
