### ISSUE TITLE
Some Related Work

### ISSUE THREAD

**Issue by Chen-Yang-Liu** [Jack-bo1220/Awesome-Remote-Sensing-Foundation-Models#33]
**This repository is very good!! I found some related work:**

(1) Remote Sensing Vision-Language Foundation Models:
- **A Decoupling Paradigm with Prompt Learning for Remote Sensing Image Change Captioning** [[paper]](https://ieeexplore.ieee.org/document/10271701) [[code]](https://github.com/Chen-Yang-Liu/PromptCC)
  - Liu C, Zhao R, Chen J, et al.
  - (2023.10) IEEE Transactions on Geoscience and Remote Sensing
 
(2) Remote Sensing Agents:
- **Change-Agent: Toward Interactive Comprehensive Remote Sensing Change Interpretation and Analysis** [[paper]](https://ieeexplore.ieee.org/abstract/document/10591792) [[code]](https://github.com/Chen-Yang-Liu/Change-Agent)
  - (2024. 03) IEEE Transactions on Geoscience and Remote Sensing

**Comment by Jack-bo1220** [comment]
Thanks a lot! we have added them.
