### ISSUE TITLE
EarthPT: a foundation model for Earth Observation

### ISSUE THREAD

**Issue by Smith42** [Jack-bo1220/Awesome-Remote-Sensing-Foundation-Models#4]
Here's an earth observation foundation model trained to predict satellite imagery time series.

https://arxiv.org/abs/2309.07207

**Comment by Jack-bo1220** [comment]
Thanks. A great job！ 
I have added relevant information about EarthPT. 
(In the future, I plan to rearrange the list based on the publication time of the papers and add more useful information)

If you have any questions, please let me know. Thanks a lot again.
