### ISSUE TITLE
Potential Collaboration Opportunity on Remote Sensing Repository

### ISSUE THREAD

**Issue by hfangcat** [Jack-bo1220/Awesome-Remote-Sensing-Foundation-Models#5]
Hi Bo,

I'm Heng, working on a project closely related to your excellent work in this repo. I have been working on a GitHub repo (private repo now) and will make it public this month. My repo mainly focuses on the vision aspect and datasets in remote sensing foundation models. I noticed some overlaps and complementaries with your work.

I am planning to cross-reference your repo as it aligns well with parts of my project, and I believe our audiences could benefit from both resources. Before doing so, I wanted to reach out to see if you're open to this idea and to share thoughts on potential synergies between our projects.

Looking forward to any feedback or ideas for collaboration!

Best,
Heng

**Comment by hfangcat** [comment]
Hi Bo, 

I'm interested in discussing a potential collaboration but I couldn't find your contact details on GitHub. Could you please share your preferred contact method, such as email or WeChat? I appreciate your consideration!

Thanks,
Heng

**Comment by Jack-bo1220** [comment]
Hi Heng，
My email：bodang@whu.edu.cn
Looking forward to your cooperation.

Best regards,
Bo Dang

> Hi Bo,
> 
> I'm interested in discussing a potential collaboration but I couldn't find your contact details on GitHub. Could you please share your preferred contact method, such as email or WeChat? I appreciate your consideration!
> 
> Thanks, Heng

**Comment by hfangcat** [comment]
Hi Bo,

I sent you an email two days ago, mentioned here just in case my email goes into spam.

Best,
Heng
